/**:
  ros__parameters:
    joints_map:
      left_front:
        - front_left_shoulder
        - front_left_leg
        - front_left_foot

      right_front:
        - front_right_shoulder
        - front_right_leg
        - front_right_foot

      left_hind:
        - rear_left_shoulder
        - rear_left_leg
        - rear_left_foot

      right_hind:
        - rear_right_shoulder
        - rear_right_leg
        - rear_right_foot